project:
  type: default

bibliography: references.bib
# Make sure pandoc can resolve figure paths from any include source.
resource-path:
  - .
  - sections
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/nature.csl

format:
  html:
    include-before-body:
      - _version-banner.html
    toc: true
    toc-depth: 3
    number-sections: true
    theme: cosmo
    embed-resources: true
  pdf:
    documentclass: article
    papersize: letter
    geometry:
      - margin=1in
    toc: false
    number-sections: true
    colorlinks: true
    fig-pos: "H"
    keep-tex: true
  docx:
    toc: false
    number-sections: true

execute:
  echo: false
  warning: false
